### ISSUE TITLE
Can the AppImage be downloaded somewhere?

### ISSUE THREAD

**Issue by probonopd** [AxelTerizaki/karaokemugen-app#15] opened 2020-08-16 13:37 UTC
Can the AppImage be downloaded somewhere? We would like to add it to https://appimage.github.io/.

**Comment by AxelTerizaki** [comment] 2020-08-16 14:18
Hello :) 

We don't build appImages anymore since they were pretty difficult to debug (we don't have anyone with a linux OS to debug it properly) so we reverted to building .deb files instead.

If you wish to help debug the appImage build, we'd be really grateful.

**Comment by probonopd** [comment] 2020-08-16 14:36
> If you wish to help debug the appImage build,

What is wrong/broken? Do you have an error message?

**Comment by AxelTerizaki** [comment] 2020-08-16 15:51
The main issue is that the app needs a postgresql to run. We usually provide one for Mac and Windows builds, but not for Linux ones, so either we do that in the appImage in some way... same issue (but less problematic) for ffmpeg and mpv.

So we'd need to bundle a version of those in the app image along with Karaoke Mugen.

**Comment by probonopd** [comment] 2020-08-16 15:54
Yes, you'd need to bundle ffmpeg, mpv, and postgresSQL.

**Comment by AxelTerizaki** [comment] 2020-08-16 16:32
Yep, the problem is, as I said, as we don't have anyone with a linux system somewhere to test it out and make sure the bundled binaries work well.

**Comment by AxelTerizaki** [comment] 2021-03-06 08:56
Closing this since we're not offering appImages anymore, only deb, tar.gz and aur packages.

**Closed** 2021-03-06 08:56 UTC
